# Generated by Django 2.2 on 2020-07-02 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alunos',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
